export const brands =
[
    { "id": 1, "nombre": "Toyota", 
    "modelos":[
        { "modelo": "Hilux" },
        { "modelo": "Corolla" },
        { "modelo": "Etios" },
        { "modelo": "SW4" },
        { "modelo": "Yaris" },
        { "modelo": "C-HR" },
        { "modelo": "Camry" },
        { "modelo": "RAV4" },
        { "modelo": "Highlander" },
        { "modelo": "Tacoma" },
        { "modelo": "Tundra" },
        { "modelo": "Prius" },
        { "modelo": "4Runner" },
        { "modelo": "Sienna" },
        { "modelo": "Land Cruiser" }
      ]},
    { "id": 2, "nombre": "Volkswagen", 
    "modelos":[
        { "modelo": "Golf" },
        { "modelo": "Polo" },
        { "modelo": "Tiguan" },
        { "modelo": "Passat" },
        { "modelo": "Jetta" },
        { "modelo": "Arteon" },
        { "modelo": "Up!" },
        { "modelo": "Beetle" },
        { "modelo": "Gol" },
        { "modelo": "Vento" },
        { "modelo": "Amarok" },
        { "modelo": "Transporter" },
        { "modelo": "Caddy" },
        { "modelo": "T-Cross" },
        { "modelo": "Touareg" },
        { "modelo": "Teramont" },
        { "modelo": "Nivus" },
        { "modelo": "Virtus" },
        { "modelo": "Saveiro" },
        { "modelo": "Fox" },
        { "modelo": "Taos" }
      ]},
    { "id": 3, "nombre": "Ford", "modelos":[
        { "modelo": "Mustang" },
        { "modelo": "Focus" },
        { "modelo": "Fiesta" },
        { "modelo": "Escape" },
        { "modelo": "Explorer" },
        { "modelo": "Ranger" },
        { "modelo": "F-150" },
        { "modelo": "Edge" },
        { "modelo": "Bronco" },
        { "modelo": "EcoSport" },
        { "modelo": "Ka" },
        { "modelo": "Transit" },
        { "modelo": "Mondeo" },
        { "modelo": "Kuga" },
        { "modelo": "Everest" },
        { "modelo": "Puma" },
        { "modelo": "Territory" },
        { "modelo": "Falcon" },
        { "modelo": "Tourneo" },
        { "modelo": "Figo" },
        { "modelo": "Raptor" }
      ] },
    { "id": 4, "nombre": "Chevrolet", "modelos":[
        { "modelo": "Camaro" },
        { "modelo": "Cruze" },
        { "modelo": "Onix" },
        { "modelo": "Equinox" },
        { "modelo": "Trailblazer" },
        { "modelo": "S10" },
        { "modelo": "Tahoe" },
        { "modelo": "Silverado" },
        { "modelo": "Spark" },
        { "modelo": "Trax" },
        { "modelo": "Malibu" },
        { "modelo": "Blazer" },
        { "modelo": "Corsa" },
        { "modelo": "Aveo" },
        { "modelo": "Tracker" },
        { "modelo": "Captiva" },
        { "modelo": "Celta" },
        { "modelo": "Prisma" },
        { "modelo": "Spin" },
        { "modelo": "Montana" }
      ] },
    { "id": 5, "nombre": "Honda", "modelos":[
        { "modelo": "Civic" },
        { "modelo": "Accord" },
        { "modelo": "CR-V" },
        { "modelo": "HR-V" },
        { "modelo": "Pilot" },
        { "modelo": "Odyssey" },
        { "modelo": "City" },
        { "modelo": "Fit" },
        { "modelo": "Jazz" },
        { "modelo": "Ridgeline" },
        { "modelo": "Crosstour" },
        { "modelo": "Insight" },
        { "modelo": "BR-V" },
        { "modelo": "WR-V" },
        { "modelo": "Brio" },
        { "modelo": "Amaze" },
        { "modelo": "C-RV" },
        { "modelo": "Freed" },
        { "modelo": "Mobilio" },
        { "modelo": "NSX" }
      ] },
    { "id": 6, "nombre": "Nissan", "modelos":[
        { "modelo": "Altima" },
        { "modelo": "Sentra" },
        { "modelo": "Maxima" },
        { "modelo": "Versa" },
        { "modelo": "Rogue" },
        { "modelo": "Murano" },
        { "modelo": "Pathfinder" },
        { "modelo": "X-Trail" },
        { "modelo": "Qashqai" },
        { "modelo": "Kicks" },
        { "modelo": "Frontier" },
        { "modelo": "Navara" },
        { "modelo": "Titan" },
        { "modelo": "370Z" },
        { "modelo": "GT-R" },
        { "modelo": "Juke" },
        { "modelo": "Micra" },
        { "modelo": "March" },
        { "modelo": "Note" },
        { "modelo": "Leaf" }
      ] },
    { "id": 7, "nombre": "BMW", "modelos":[
        { "modelo": "Serie 3" },
        { "modelo": "Serie 5" },
        { "modelo": "Serie 7" },
        { "modelo": "X1" },
        { "modelo": "X3" },
        { "modelo": "X5" },
        { "modelo": "X6" },
        { "modelo": "X7" },
        { "modelo": "Z4" },
        { "modelo": "i3" },
        { "modelo": "i8" },
        { "modelo": "M2" },
        { "modelo": "M3" },
        { "modelo": "M4" },
        { "modelo": "M5" },
        { "modelo": "M8" },
        { "modelo": "X2" },
        { "modelo": "X4" },
        { "modelo": "X6 M" },
        { "modelo": "8 Series" }
      ] },
    { "id": 8, "nombre": "Mercedes-Benz", "modelos":[
        { "modelo": "Clase A" },
        { "modelo": "Clase C" },
        { "modelo": "Clase E" },
        { "modelo": "Clase S" },
        { "modelo": "GLA" },
        { "modelo": "GLC" },
        { "modelo": "GLE" },
        { "modelo": "GLS" },
        { "modelo": "CLA" },
        { "modelo": "CLS" },
        { "modelo": "AMG GT" },
        { "modelo": "G" },
        { "modelo": "GLB" },
        { "modelo": "GLC Coupé" },
        { "modelo": "GLE Coupé" },
        { "modelo": "GLS" },
        { "modelo": "SLS AMG" },
        { "modelo": "EQC" },
        { "modelo": "Vito" },
        { "modelo": "Sprinter" }
      ] },
    { "id": 9, "nombre": "Audi", "modelos":[
        { "modelo": "A1" },
        { "modelo": "A3" },
        { "modelo": "A4" },
        { "modelo": "A5" },
        { "modelo": "A6" },
        { "modelo": "A7" },
        { "modelo": "A8" },
        { "modelo": "Q2" },
        { "modelo": "Q3" },
        { "modelo": "Q5" },
        { "modelo": "Q7" },
        { "modelo": "Q8" },
        { "modelo": "TT" },
        { "modelo": "R8" },
        { "modelo": "RS3" },
        { "modelo": "RS4" },
        { "modelo": "RS5" },
        { "modelo": "RS6" },
        { "modelo": "RS7" },
        { "modelo": "e-tron" },
        { "modelo": "S3" }
      ] },
    { "id": 10, "nombre": "Hyundai", "modelos":[
        { "modelo": "Accent" },
        { "modelo": "Elantra" },
        { "modelo": "Sonata" },
        { "modelo": "Genesis" },
        { "modelo": "Veloster" },
        { "modelo": "Tucson" },
        { "modelo": "Santa Fe" },
        { "modelo": "Palisade" },
        { "modelo": "Kona" },
        { "modelo": "Venue" },
        { "modelo": "IONIQ" },
        { "modelo": "Nexo" },
        { "modelo": "i10" },
        { "modelo": "i20" },
        { "modelo": "i30" },
        { "modelo": "i40" },
        { "modelo": "Sta Fe" },
        { "modelo": "Creta" },
        { "modelo": "Azera" },
        { "modelo": "Verna" }
      ] },
    { "id": 11, "nombre": "Kia", "modelos":[
        { "modelo": "Rio" },
        { "modelo": "Forte" },
        { "modelo": "Optima" },
        { "modelo": "Stinger" },
        { "modelo": "Ceed" },
        { "modelo": "Seltos" },
        { "modelo": "Sportage" },
        { "modelo": "Sorento" },
        { "modelo": "Telluride" },
        { "modelo": "Soul" },
        { "modelo": "Niro" },
        { "modelo": "Carnival" },
        { "modelo": "Stonic" },
        { "modelo": "Picanto" },
        { "modelo": "Cerato" },
        { "modelo": "Mohave" },
        { "modelo": "Quoris" },
        { "modelo": "Optima" },
        { "modelo": "K5" },
        { "modelo": "K9" }
      ] },
    { "id": 12, "nombre": "Subaru", "modelos":[
        { "modelo": "Impreza" },
        { "modelo": "Legacy" },
        { "modelo": "Outback" },
        { "modelo": "Forester" },
        { "modelo": "Crosstrek" },
        { "modelo": "Ascent" },
        { "modelo": "BRZ" },
        { "modelo": "WRX" },
        { "modelo": "XV" },
        { "modelo": "Levorg" },
        { "modelo": "Justy" },
        { "modelo": "Trezia" },
        { "modelo": "Exiga" },
        { "modelo": "Baja" },
        { "modelo": "Tribeca" },
        { "modelo": "SVX" },
        { "modelo": "R1" },
        { "modelo": "R2" },
        { "modelo": "Alcyone" },
        { "modelo": "Vivio" }
      ] },
    { "id": 13, "nombre": "Tesla", "modelos":[
        { "modelo": "Model S" },
        { "modelo": "Model 3" },
        { "modelo": "Model X" },
        { "modelo": "Model Y" },
        { "modelo": "Roadster" },
        { "modelo": "Cybertruck" },
        { "modelo": "Semi" },
        { "modelo": "Model B" },
        { "modelo": "Model C" },
        { "modelo": "Model D" },
        { "modelo": "Model F" },
        { "modelo": "Model G" },
        { "modelo": "Model H" },
        { "modelo": "Model J" },
        { "modelo": "Model L" },
        { "modelo": "Model M" },
        { "modelo": "Model P" },
        { "modelo": "Model R" },
        { "modelo": "Model T" },
        { "modelo": "Model V" }
      ] },
    { "id": 14, "nombre": "Volvo","modelos":[
        { "modelo": "XC40" },
        { "modelo": "XC60" },
        { "modelo": "XC90" },
        { "modelo": "S60" },
        { "modelo": "S90" },
        { "modelo": "V60" },
        { "modelo": "V90" },
        { "modelo": "V40" },
        { "modelo": "V40 Cross Country" },
        { "modelo": "V60 Cross Country" },
        { "modelo": "V90 Cross Country" },
        { "modelo": "C40 Recharge" },
        { "modelo": "C30" },
        { "modelo": "C70" },
        { "modelo": "Polestar 1" },
        { "modelo": "Polestar 2" },
        { "modelo": "Polestar 3" },
        { "modelo": "Polestar 4" },
        { "modelo": "Polestar 5" },
        { "modelo": "Polestar 6" }
      ] },
    { "id": 15, "nombre": "Mazda", "modelos":[] },
    { "id": 16, "nombre": "Land Rover", "modelos":[] },
    { "id": 17, "nombre": "Jaguar", "modelos":[] },
    { "id": 18, "nombre": "Porsche", "modelos":[
        { "modelo": "911" },
        { "modelo": "Cayman" },
        { "modelo": "Boxster" },
        { "modelo": "Panamera" },
        { "modelo": "Macan" },
        { "modelo": "Cayenne" },
        { "modelo": "Taycan" },
        { "modelo": "718" },
        { "modelo": "911 GT" },
        { "modelo": "911 Turbo" },
        { "modelo": "911 GT3" },
        { "modelo": "911 GT2" },
        { "modelo": "911 R" },
        { "modelo": "911 Targa" },
        { "modelo": "Cayenne Coupe" },
        { "modelo": "Cayman GT4" },
        { "modelo": "Boxster Spyder" },
        { "modelo": "Panamera Sport Turismo" },
        { "modelo": "Macan GTS" },
        { "modelo": "911 Carrera" }
      ] },
    { "id": 19, "nombre": "Fiat", "modelos":[
        { "modelo": "500" },
        { "modelo": "Panda" },
        { "modelo": "Tipo" },
        { "modelo": "Punto" },
        { "modelo": "500X" },
        { "modelo": "500L" },
        { "modelo": "Ducato" },
        { "modelo": "Tipo Cross" },
        { "modelo": "Tipo Sport" },
        { "modelo": "Spider" },
        { "modelo": "Toro" },
        { "modelo": "Argo" },
        { "modelo": "Mobi" },
        { "modelo": "Uno" },
        { "modelo": "Linea" },
        { "modelo": "Cronos" },
        { "modelo": "Fiorino" },
        { "modelo": "Siena" },
        { "modelo": "Palio" },
        { "modelo": "500e" }
      ] },
    { "id": 20, "nombre": "Peugeot", "modelos":[
        { "modelo": "208" },
        { "modelo": "308" },
        { "modelo": "2008" },
        { "modelo": "3008" },
        { "modelo": "5008" },
        { "modelo": "508" },
        { "modelo": "Partner" },
        { "modelo": "Rifter" },
        { "modelo": "Traveller" },
        { "modelo": "Expert" },
        { "modelo": "Boxer" },
        { "modelo": "108" },
        { "modelo": "208 GTI" },
        { "modelo": "308 GT" },
        { "modelo": "3008 GT" },
        { "modelo": "508 GT" },
        { "modelo": "e-208" },
        { "modelo": "e-2008" },
        { "modelo": "e-308" },
        { "modelo": "e-3008" }
      ] },
    { "id": 21, "nombre": "Mitsubishi", "modelos":[
        { "modelo": "Lancer" },
        { "modelo": "Outlander" },
        { "modelo": "Eclipse Cross" },
        { "modelo": "Pajero" },
        { "modelo": "ASX" },
        { "modelo": "Mirage" },
        { "modelo": "Triton" },
        { "modelo": "XPANDER" },
        { "modelo": "Attrage" },
        { "modelo": "RVR" },
        { "modelo": "Strada" },
        { "modelo": "Delica" },
        { "modelo": "i-MiEV" },
        { "modelo": "Colt" },
        { "modelo": "Galant" },
        { "modelo": "Shogun" },
        { "modelo": "Space Star" },
        { "modelo": "L200" },
        { "modelo": "Pajero Sport" },
        { "modelo": "Grandis" }
      ] },
    { "id": 22, "nombre": "Suzuki", "modelos":[
        { "modelo": "Swift" },
        { "modelo": "Vitara" },
        { "modelo": "Jimny" },
        { "modelo": "Celerio" },
        { "modelo": "Baleno" },
        { "modelo": "Ignis" },
        { "modelo": "S-Cross" },
        { "modelo": "SX4" },
        { "modelo": "Alto" },
        { "modelo": "Ertiga" },
        { "modelo": "Splash" },
        { "modelo": "Swift Sport" },
        { "modelo": "Ciaz" },
        { "modelo": "Grand Vitara" },
        { "modelo": "XL6" },
        { "modelo": "Across" },
        { "modelo": "Samurai" },
        { "modelo": "Kizashi" },
        { "modelo": "Wagon R" },
        { "modelo": "Solio" }
      ] },
    { "id": 23, "nombre": "Renault", "modelos":[
        { "modelo": "Clio" },
        { "modelo": "Megane" },
        { "modelo": "Captur" },
        { "modelo": "Kadjar" },
        { "modelo": "Scenic" },
        { "modelo": "Talisman" },
        { "modelo": "Zoe" },
        { "modelo": "Twingo" },
        { "modelo": "Koleos" },
        { "modelo": "Laguna" },
        { "modelo": "Duster" },
        { "modelo": "Fluence" },
        { "modelo": "Sandero" },
        { "modelo": "Logan" },
        { "modelo": "Symbol" },
        { "modelo": "Kangoo" },
        { "modelo": "Grand Scenic" },
        { "modelo": "Espace" },
        { "modelo": "Alaskan" },
        { "modelo": "Arkana" }
      ] },
    { "id": 24, "nombre": "Mini", "modelos":[] },
    { "id": 25, "nombre": "Lexus", "modelos":[]  },
    { "id": 26, "nombre": "Acura", "modelos":[]  },
    { "id": 27, "nombre": "Alfa Romeo", "modelos":[]  },
    { "id": 28, "nombre": "Aston Martin", "modelos":[]  },
    { "id": 29, "nombre": "Bentley", "modelos":[]  },
    { "id": 30, "nombre": "Bugatti", "modelos":[]  },
    { "id": 31, "nombre": "Buick", "modelos":[]  },
    { "id": 32, "nombre": "Cadillac", "modelos":[]  },
    { "id": 33, "nombre": "Chrysler", "modelos":[]  },
    { "id": 34, "nombre": "Citroën", "modelos":[
        { "modelo": "C3" },
        { "modelo": "C4" },
        { "modelo": "C5" },
        { "modelo": "Cactus" },
        { "modelo": "Berlingo" },
        { "modelo": "Jumpy" },
        { "modelo": "Spacetourer" },
        { "modelo": "C1" },
        { "modelo": "C2" },
        { "modelo": "C3 Aircross" },
        { "modelo": "C4 Cactus" },
        { "modelo": "C4 Picasso" },
        { "modelo": "Grand C4 Picasso" },
        { "modelo": "DS 3" },
        { "modelo": "DS 4" },
        { "modelo": "DS 5" },
        { "modelo": "DS 7" },
        { "modelo": "Ami" },
        { "modelo": "Ë-C4" },
        { "modelo": "Ë-Jumpy" }
      ] },
    { "id": 35, "nombre": "Dacia", "modelos":[] },
    { "id": 36, "nombre": "Dodge", "modelos":[
        { "modelo": "Charger" },
        { "modelo": "Challenger" },
        { "modelo": "Durango" },
        { "modelo": "Journey" },
        { "modelo": "Grand Caravan" },
        { "modelo": "Dakota" },
        { "modelo": "Ram 1500" },
        { "modelo": "Ram 2500" },
        { "modelo": "Ram 3500" },
        { "modelo": "Viper" },
        { "modelo": "Dart" },
        { "modelo": "Caliber" },
        { "modelo": "Avenger" },
        { "modelo": "Nitro" },
        { "modelo": "Magnum" },
        { "modelo": "Intrepid" },
        { "modelo": "Neon" },
        { "modelo": "Stratus" },
        { "modelo": "Stealth" },
        { "modelo": "SRT-4" }
      ] },
    { "id": 37, "nombre": "Ferrari", "modelos":[] },
    { "id": 38, "nombre": "Genesis", "modelos":[] },
    { "id": 39, "nombre": "GMC", "modelos":[
        { "modelo": "Sierra" },
        { "modelo": "Yukon" },
        { "modelo": "Terrain" },
        { "modelo": "Acadia" },
        { "modelo": "Canyon" },
        { "modelo": "Savana" },
        { "modelo": "Denali" },
        { "modelo": "Envoy" },
        { "modelo": "Jimmy" },
        { "modelo": "Sonoma" },
        { "modelo": "Topkick" },
        { "modelo": "Typhoon" },
        { "modelo": "Vandura" },
        { "modelo": "G-Series" },
        { "modelo": "Syclone" },
        { "modelo": "Rally" },
        { "modelo": "Suburban" },
        { "modelo": "Terra" },
        { "modelo": "Yukon XL" },
        { "modelo": "Arcadia" }
      ] },
    { "id": 40, "nombre": "Infiniti", "modelos":[] },
    { "id": 41, "nombre": "Isuzu", "modelos":[] },
    { "id": 42, "nombre": "Jeep", "modelos":[
        { "modelo": "Wrangler" },
        { "modelo": "Grand Cherokee" },
        { "modelo": "Cherokee" },
        { "modelo": "Compass" },
        { "modelo": "Renegade" },
        { "modelo": "Gladiator" },
        { "modelo": "Commander" },
        { "modelo": "Patriot" },
        { "modelo": "Liberty" },
        { "modelo": "Wagoneer" },
        { "modelo": "Grand Wagoneer" },
        { "modelo": "Jeepster" },
        { "modelo": "CJ" },
        { "modelo": "Scrambler" },
        { "modelo": "J10" },
        { "modelo": "J20" },
        { "modelo": "DJ" },
        { "modelo": "Comanche" },
        { "modelo": "FC" },
        { "modelo": "Forward Control" }
      ] },
    { "id": 43, "nombre": "Lamborghini", "modelos":[] },
    { "id": 44, "nombre": "Lancia", "modelos":[] },
    { "id": 45, "nombre": "Lincoln", "modelos":[] },
    { "id": 46, "nombre": "Lotus", "modelos":[] },
    { "id": 47, "nombre": "Maserati", "modelos":[] },
    { "id": 48, "nombre": "Maybach", "modelos":[] },
    { "id": 49, "nombre": "McLaren" , "modelos":[]},
    { "id": 50, "nombre": "Mitsubishi", "modelos":[]}
  ]